updates for social page in the new folder structure
Peerprotocol/peer-on-strk pull request #65
Opened 2024-11-25 10:08 UTC by akintola4

# moved all code for questPage to socials
# deleted older questPage

2024-11-25 10:17 UTC, Dprof-in-tech requested changes
Also, move all your components into the components folder /quests/component. and make sure the code is running before pushing a new commit into this PR

2024-11-25 10:17 UTC, Dprof-in-tech commented on frontend/src/app/app/quests/socials/page.tsx
> +'use client'
eslint errors and it doesnt work

2024-11-25 10:17 UTC, Dprof-in-tech commented on frontend/src/app/app/quests/socials/layout.tsx
>  import { usePathname } from 'next/navigation'
why do you need a layout file? look at the structure for the profile/page.tsx and see how the sidebar was implemented there.

2024-11-25 18:33 UTC, DanielEmmanuel1 commented
Looks good to me @akintola4

2024-11-25 18:34 UTC, merged

2024-11-26 05:18 UTC, akintola4 commented
Thank you sir